# TP 1: LDA/QDA y optimización matemática de modelos

Se puede consultar la introducción teórica en el mono-notebook, se prefiere mantener este lo más chico posible.

In [2]:
# imports
import numpy as np
import numpy.linalg as LA

from base.qda import QDA, TensorizedQDA, FasterQDA, EfficientQDA
from base.cholesky import QDA_Chol1, QDA_Chol2, QDA_Chol3
from utils.bench import Benchmark
from utils.datasets import (get_iris_dataset, get_letters_dataset, 
                            get_penguins_dataset, get_wine_dataset,
                            label_encode)

## Comparación benchmarks

In [9]:
X_full, y_full = get_letters_dataset()

X_full.shape, y_full.shape

((20000, 16), (20000, 1))

In [10]:
# encodeamos a número las clases
y_full_encoded = label_encode(y_full)

y_full[:5], y_full_encoded[:5]

(array([['Z'],
        ['P'],
        ['S'],
        ['H'],
        ['H']], dtype=object),
 array([[25],
        [15],
        [18],
        [ 7],
        [ 7]]))

In [11]:
# generamos el benchmark
# observar que son valores muy bajos de runs para que corra rápido ahora
b = Benchmark(
    X_full, y_full_encoded,
    n_runs = 50,
    warmup = 10,
    mem_runs = 5,
    test_sz = 0.3,
    same_splits = False
)

Benching params:
Total runs: 65
Warmup runs: 10
Peak Memory usage runs: 5
Running time runs: 50
Train size rows (approx): 14000
Test size rows (approx): 6000
Test size fraction: 0.3

In [12]:
# bencheamos un par
to_bench = [QDA, TensorizedQDA, FasterQDA, EfficientQDA]

for model in to_bench:
    b.bench(model)

QDA (MEM):   0%|          | 0/5 [00:00<?, ?it/s]

QDA (TIME):   0%|          | 0/50 [00:00<?, ?it/s]

TensorizedQDA (MEM):   0%|          | 0/5 [00:00<?, ?it/s]

TensorizedQDA (TIME):   0%|          | 0/50 [00:00<?, ?it/s]

FasterQDA (MEM):   0%|          | 0/5 [00:00<?, ?it/s]

FasterQDA (TIME):   0%|          | 0/50 [00:00<?, ?it/s]

EfficientQDA (MEM):   0%|          | 0/5 [00:00<?, ?it/s]

EfficientQDA (TIME):   0%|          | 0/50 [00:00<?, ?it/s]

In [13]:
# hacemos un summary
summ = b.summary()
summ[['train_median_ms', 'test_median_ms', 'train_mem_median_mb', 'test_mem_median_mb']]

,train_median_ms,test_median_ms,train_mem_median_mb,test_mem_median_mb
model,,,,
QDA,5.102924,1553.993628,0.252525,0.114967
TensorizedQDA,4.982413,287.111327,0.249184,0.169373
FasterQDA,9.103185,2591.977603,0.251015,7179.315666
EfficientQDA,4.389455,15.469758,0.250893,39.392891

## Conclusiones (consigna #7)
- `train_median_ms`: es prácticamente el mismo para todos los modelos, lo cual está bien porque el código es el mismo.
- `test_median_ms`: esta sección es una de las más importantes, acá sí podemos apreciar cómo varía el tiempo de ejecución. Más específicamente, se puede apreciar cómo fuimos reduciendo considerablemente y, por ende, mejorando en cada modelo.
- `test_mem_median_mb`: esta sección también es de las más importantes, acá podemos apreciar cómo cambiar el consumo de memoria para cada modelo. A resaltar, FasterQDA consume una mucho mayor que sus pares: 56 veces más que TensorizedQDA. Esto es muy importante y a considerar para dataset de gran tamaño. En cuanto a EfficientQDA, podemos ver que consume más memoria que TensorizedQDA (8x), pero al mismo tiempo es considerablemente más rápido (24x)

En líneas generales, podemos observar cómo EfficientQDA ofrece una muy buena relación en cuanto a tiempo de procesamiento y memoria utilizada. Para el modelo de FasterQDA, que al eliminar el loop en la predicción y utilizar todo el dataset para el cálculo, logramos mejorar considerablemente el tiempo de ejecución, pero a costa de un consumo de memoria muy elevado.

Las observaciones condicen con lo esperado y sorprende el hecho de las grandes mejoras que se logra aplicando soluciones con un trasfondo matemático.

## Consigna #11 - Comparar modelos QDA y Choleski

In [14]:
# Volvemos a correr nuestro bench
b = Benchmark(
    X_full, y_full_encoded,
    n_runs = 50,
    warmup = 10,
    mem_runs = 5,
    test_sz = 0.3,
    same_splits = False
)

to_bench = [
    QDA, 
    TensorizedQDA, 
    FasterQDA, 
    EfficientQDA,
    QDA_Chol1,
    QDA_Chol2,
    QDA_Chol3
]

for model in to_bench:
    b.bench(model)

Benching params:
Total runs: 65
Warmup runs: 10
Peak Memory usage runs: 5
Running time runs: 50
Train size rows (approx): 14000
Test size rows (approx): 6000
Test size fraction: 0.3

QDA (MEM):   0%|          | 0/5 [00:00<?, ?it/s]

QDA (TIME):   0%|          | 0/50 [00:00<?, ?it/s]

TensorizedQDA (MEM):   0%|          | 0/5 [00:00<?, ?it/s]

TensorizedQDA (TIME):   0%|          | 0/50 [00:00<?, ?it/s]

FasterQDA (MEM):   0%|          | 0/5 [00:00<?, ?it/s]

FasterQDA (TIME):   0%|          | 0/50 [00:00<?, ?it/s]

EfficientQDA (MEM):   0%|          | 0/5 [00:00<?, ?it/s]

EfficientQDA (TIME):   0%|          | 0/50 [00:00<?, ?it/s]

QDA_Chol1 (MEM):   0%|          | 0/5 [00:00<?, ?it/s]

QDA_Chol1 (TIME):   0%|          | 0/50 [00:00<?, ?it/s]

QDA_Chol2 (MEM):   0%|          | 0/5 [00:00<?, ?it/s]

QDA_Chol2 (TIME):   0%|          | 0/50 [00:00<?, ?it/s]

QDA_Chol3 (MEM):   0%|          | 0/5 [00:00<?, ?it/s]

QDA_Chol3 (TIME):   0%|          | 0/50 [00:00<?, ?it/s]

In [15]:
summ = b.summary()
summ[['train_median_ms', 'test_median_ms', 'train_mem_median_mb', 'test_mem_median_mb']]

,train_median_ms,test_median_ms,train_mem_median_mb,test_mem_median_mb
model,,,,
QDA,5.074918,1549.311070,0.251381,0.113912
TensorizedQDA,5.041359,284.318449,0.249184,0.169373
FasterQDA,10.475264,2596.798534,0.251015,7179.315666
EfficientQDA,5.416305,16.736621,0.250893,39.392891
QDA_Chol1,5.876912,853.999316,0.251236,0.111382
QDA_Chol2,5.487125,2225.167938,0.249504,0.111862
QDA_Chol3,5.336476,857.275527,0.249397,0.111290

**Conclusiones**

Habiendo corriedo el bench para todos los modelos de QDA y Choleski, podemos observar que en lineas generales EfficientQDA sigue siendo el modelo que presenta una "mejor" relacion de tiempo y memoria ocupada.

- Los modelos de Choleski usan la misma cantidad de memoria que QDA, lo que tiene sentido porque estan usando basicamenta las mismas estrucutras de datos.

En la siguiente tabla vemos la comparacion del tiempo:


| Modelo                | Tiempo (ms) | Comparado con QDA |
  |-----------------------|-------------|-------------------|
  | EfficientQDA          | ~17         | ~90× más rápido   |
  | TensorizedQDA         | ~284        | ~5× más rápido    |
  | QDA_Chol1 y QDA_Chol3 | ~855        | ~1.8× más rápidos |
  | QDA                   | ~1549       | referencia        |
  | QDA_Chol2             | ~2225       | ~1.4× más lento   |
  | FasterQDA             | ~2597       | ~1.7× más lento   |