# TP 1: LDA/QDA y optimización matemática de modelos

Se puede consultar la introducción teórica en el mono-notebook, se prefiere mantener este lo más chico posible.

In [13]:
# imports
import numpy as np
import numpy.linalg as LA

import importlib
import base.qda, base.cholesky
# forzamos la recarga de los modulos, por si se editaron los .py con el kernel ya iniciado
importlib.reload(base.qda)
importlib.reload(base.cholesky)

from base.qda import QDA, TensorizedQDA, FasterQDA, EfficientQDA
from base.cholesky import QDA_Chol1, QDA_Chol2, QDA_Chol3
from utils.bench import Benchmark
from utils.datasets import (get_iris_dataset, get_letters_dataset, 
                            get_penguins_dataset, get_wine_dataset,
                            label_encode)

## Comparación benchmarks

In [31]:
X_full, y_full = get_wine_dataset()

X_full.shape, y_full.shape

((178, 13), (178, 1))

In [32]:
# encodeamos a número las clases
y_full_encoded = label_encode(y_full)

y_full[:5], y_full_encoded[:5]

(array([['class_0'],
        ['class_0'],
        ['class_0'],
        ['class_0'],
        ['class_0']], dtype='<U7'),
 array([[0],
        [0],
        [0],
        [0],
        [0]]))

In [33]:
# generamos el benchmark
# observar que son valores muy bajos de runs para que corra rápido ahora
b = Benchmark(
    X_full, y_full_encoded,
    n_runs = 100,
    warmup = 20,
    mem_runs = 30,
    test_sz = 0.2,
    same_splits = False
)

Benching params:
Total runs: 150
Warmup runs: 20
Peak Memory usage runs: 30
Running time runs: 100
Train size rows (approx): 143
Test size rows (approx): 35
Test size fraction: 0.2

In [34]:
# bencheamos un par
to_bench = [QDA, TensorizedQDA, FasterQDA, EfficientQDA]

for model in to_bench:
    b.bench(model)

QDA (MEM):   0%|          | 0/30 [00:00<?, ?it/s]

QDA (TIME):   0%|          | 0/100 [00:00<?, ?it/s]

TensorizedQDA (MEM):   0%|          | 0/30 [00:00<?, ?it/s]

TensorizedQDA (TIME):   0%|          | 0/100 [00:00<?, ?it/s]

FasterQDA (MEM):   0%|          | 0/30 [00:00<?, ?it/s]

FasterQDA (TIME):   0%|          | 0/100 [00:00<?, ?it/s]

EfficientQDA (MEM):   0%|          | 0/30 [00:00<?, ?it/s]

EfficientQDA (TIME):   0%|          | 0/100 [00:00<?, ?it/s]

In [35]:
# hacemos un summary
summ = b.summary()
summ[['train_median_ms', 'test_median_ms', 'train_mem_median_mb', 'test_mem_median_mb']]

,train_median_ms,test_median_ms,train_mem_median_mb,test_mem_median_mb
model,,,,
QDA,0.245214,1.199010,0.020256,0.007560
TensorizedQDA,0.225554,0.509915,0.020278,0.011848
FasterQDA,0.223180,0.044944,0.020210,0.061325
EfficientQDA,0.231526,0.046130,0.020061,0.053558

## Conclusiones (consigna #7)
- `train_median_ms`: es prácticamente el mismo para todos los modelos, lo cual está bien porque el código es el mismo.
- `test_median_ms`: esta sección es una de las más importantes, acá sí podemos apreciar cómo varía el tiempo de ejecución. Más específicamente, se puede apreciar cómo fuimos reduciendo considerablemente y, por ende, mejorando en cada modelo.
- `test_mem_median_mb`: esta sección también es de las más importantes, acá podemos apreciar cómo cambiar el consumo de memoria para cada modelo. A resaltar, FasterQDA consume una mucho mayor que sus pares: 56 veces más que TensorizedQDA. Esto es muy importante y a considerar para dataset de gran tamaño. En cuanto a EfficientQDA, podemos ver que consume más memoria que TensorizedQDA (8x), pero al mismo tiempo es considerablemente más rápido (24x)

En líneas generales, podemos observar cómo EfficientQDA ofrece una muy buena relación en cuanto a tiempo de procesamiento y memoria utilizada. Para el modelo de FasterQDA, que al eliminar el loop en la predicción y utilizar todo el dataset para el cálculo, logramos mejorar considerablemente el tiempo de ejecución, pero a costa de un consumo de memoria muy elevado.

Las observaciones condicen con lo esperado y sorprende el hecho de las grandes mejoras que se logra aplicando soluciones con un trasfondo matemático.

## Consigna #11 - Comparar modelos QDA y Choleski

In [37]:
# Volvemos a correr nuestro bench
ben = Benchmark(
    X_full, y_full_encoded,
    n_runs = 100,
    warmup = 20,
    mem_runs = 30,
    test_sz = 0.2,
    same_splits = False
)

to_bench = [
    QDA, 
    TensorizedQDA, 
    FasterQDA, 
    EfficientQDA,
    QDA_Chol1,
    QDA_Chol2,
    QDA_Chol3
]

for model in to_bench:
   ben.bench(model)

Benching params:
Total runs: 150
Warmup runs: 20
Peak Memory usage runs: 30
Running time runs: 100
Train size rows (approx): 143
Test size rows (approx): 35
Test size fraction: 0.2

QDA (MEM):   0%|          | 0/30 [00:00<?, ?it/s]

QDA (TIME):   0%|          | 0/100 [00:00<?, ?it/s]

TensorizedQDA (MEM):   0%|          | 0/30 [00:00<?, ?it/s]

TensorizedQDA (TIME):   0%|          | 0/100 [00:00<?, ?it/s]

FasterQDA (MEM):   0%|          | 0/30 [00:00<?, ?it/s]

FasterQDA (TIME):   0%|          | 0/100 [00:00<?, ?it/s]

EfficientQDA (MEM):   0%|          | 0/30 [00:00<?, ?it/s]

EfficientQDA (TIME):   0%|          | 0/100 [00:00<?, ?it/s]

QDA_Chol1 (MEM):   0%|          | 0/30 [00:00<?, ?it/s]

QDA_Chol1 (TIME):   0%|          | 0/100 [00:00<?, ?it/s]

QDA_Chol2 (MEM):   0%|          | 0/30 [00:00<?, ?it/s]

QDA_Chol2 (TIME):   0%|          | 0/100 [00:00<?, ?it/s]

QDA_Chol3 (MEM):   0%|          | 0/30 [00:00<?, ?it/s]

QDA_Chol3 (TIME):   0%|          | 0/100 [00:00<?, ?it/s]

In [38]:
summ = ben.summary()
summ[['train_median_ms', 'test_median_ms', 'train_mem_median_mb', 'test_mem_median_mb']]

,train_median_ms,test_median_ms,train_mem_median_mb,test_mem_median_mb
model,,,,
QDA,0.225868,1.163181,0.020373,0.007738
TensorizedQDA,0.237846,0.529192,0.020359,0.011940
FasterQDA,0.219372,0.046096,0.020313,0.061325
EfficientQDA,0.226952,0.045083,0.020016,0.053558
QDA_Chol1,0.300355,0.719930,0.020424,0.007767
QDA_Chol2,0.232573,1.752611,0.020065,0.007968
QDA_Chol3,0.217347,0.692272,0.020187,0.007572

**Conclusiones**

Habiendo corriedo el bench para todos los modelos de QDA y Choleski, podemos observar que en lineas generales EfficientQDA sigue siendo el modelo que presenta una "mejor" relacion de tiempo y memoria ocupada.

- Los modelos de Choleski usan la misma cantidad de memoria que QDA, lo que tiene sentido porque estan usando basicamenta las mismas estrucutras de datos.

En la siguiente tabla vemos la comparacion del tiempo de predicción (test):


| Modelo                | Tiempo test (ms) | Comparado con QDA |
|-----------------------|------------------|-------------------|
| EfficientQDA          | ~0.045           | ~26× más rápido   |
| FasterQDA             | ~0.046           | ~25× más rápido   |
| TensorizedQDA         | ~0.53            | ~2.2× más rápido  |
| QDA_Chol1 y QDA_Chol3 | ~0.7             | ~1.6× más rápidos |
| QDA                   | ~1.16            | referencia        |
| QDA_Chol2             | ~1.75            | ~1.5× más lento   |

## Testing

Esta sección se usa para ir comprobando de que los distintos modelos realmente están prediciendo lo mismo. No es parte de la consigna.

In [14]:
from base.cholesky import TensorizedChol, EfficientChol
from utils.datasets import split_transpose

# iris es el dataset mas pequeno (150 observaciones, 4 features, 3 clases)
X_small, y_small = get_iris_dataset()
y_small = label_encode(y_small)
X_train, X_test, y_train, y_test = split_transpose(X_small, y_small, test_size=0.3, random_state=0)

models = [
    QDA, TensorizedQDA, FasterQDA, EfficientQDA,
    QDA_Chol1, QDA_Chol2, QDA_Chol3, TensorizedChol, EfficientChol
]

# entrenamos cada modelo y guardamos sus predicciones sobre el mismo test
preds = {}
trained = {}
for model in models:
    m = model()
    m.fit(X_train, y_train)
    trained[model.__name__] = m
    preds[model.__name__] = m.predict(X_test)

# QDA es la referencia: todos los demas tienen que predecir exactamente lo mismo
ref = preds['QDA']
for name, pred in preds.items():
    assert pred.shape == ref.shape, f"{name}: shape {pred.shape} != {ref.shape}"
    assert (pred == ref).all(), f"{name}: difiere de QDA en {(pred != ref).sum()} observaciones"
    print(f"{name:15s} OK  accuracy={(pred == y_test).mean():.3f}")

QDA             OK  accuracy=0.978
TensorizedQDA   OK  accuracy=0.978
FasterQDA       OK  accuracy=0.978
EfficientQDA    OK  accuracy=0.978
QDA_Chol1       OK  accuracy=0.978
QDA_Chol2       OK  accuracy=0.978
QDA_Chol3       OK  accuracy=0.978
TensorizedChol  OK  accuracy=0.978
EfficientChol   OK  accuracy=0.978

In [15]:
# comparamos los valores de log P(x|G=k), no solo la clase predicha
# referencia: QDA, evaluando observacion por observacion y clase por clase
n, k = X_test.shape[1], len(trained['QDA'].log_a_priori)

def per_obs_class(model):
    # modelos que implementan _predict_log_conditional(x, class_idx) -> matriz (n, k)
    return np.array([[float(np.squeeze(model._predict_log_conditional(X_test[:, [i]], c)))
                      for c in range(k)] for i in range(n)])

def per_obs(model):
    # modelos que implementan _predict_log_conditionals(x) (las k clases juntas) -> matriz (n, k)
    return np.array([model._predict_log_conditionals(X_test[:, [i]]) for i in range(n)])

ref_log = per_obs_class(trained['QDA'])

log_conds = {
    'QDA_Chol1': per_obs_class(trained['QDA_Chol1']),
    'QDA_Chol2': per_obs_class(trained['QDA_Chol2']),
    'QDA_Chol3': per_obs_class(trained['QDA_Chol3']),
    'TensorizedQDA': per_obs(trained['TensorizedQDA']),
    'TensorizedChol': per_obs(trained['TensorizedChol']),
    'FasterQDA': trained['FasterQDA']._predict_log_conditionals_batch(X_test).T,  # (k,n) -> (n,k)
    'EfficientChol': trained['EfficientChol']._predict_log_conditionals_batch(X_test).T,  # (k,n) -> (n,k)
}

for name, vals in log_conds.items():
    assert np.allclose(vals, ref_log), f"{name}: difiere de QDA"
    print(f"{name:15s} OK  max |diff| con QDA = {np.abs(vals - ref_log).max():.2e}")

AttributeError: 'EfficientChol' object has no attribute '_predict_log_conditionals_batch'

In [6]:
# tabla con los log P(x|G=k) de cada modelo: una fila por (observacion, clase)
import pandas as pd

n_show = 5  # primeras observaciones del test
index = pd.MultiIndex.from_product([range(n_show), range(k)], names=['obs', 'clase'])
table = pd.DataFrame(
    {'QDA': ref_log[:n_show].flatten(), **{name: vals[:n_show].flatten() for name, vals in log_conds.items()}},
    index=index
)
display(table.round(6))
print("max |diff| de cualquier modelo contra QDA:", table.sub(table['QDA'], axis=0).abs().max().max())

# clase predicha por cada modelo para las primeras 15 observaciones de test
pred_table = pd.DataFrame({name: pred.flatten() for name, pred in preds.items()})
pred_table.insert(0, 'real', y_test.flatten())
display(pred_table.head(15).T)
print("todas las predicciones coinciden:", (pred_table.drop(columns='real').nunique(axis=1) == 1).all())

                  QDA   QDA_Chol1   QDA_Chol2   QDA_Chol3  TensorizedQDA  \
obs clase
0   0     -497.025379 -497.025379 -497.025379 -497.025379    -497.025379
    1      -25.768385  -25.768385  -25.768385  -25.768385     -25.768385
    2        1.196574    1.196574    1.196574    1.196574       1.196574
1   0     -195.240930 -195.240930 -195.240930 -195.240930    -195.240930
    1        2.237160    2.237160    2.237160    2.237160       2.237160
    2      -10.876493  -10.876493  -10.876493  -10.876493     -10.876493
2   0        4.022572    4.022572    4.022572    4.022572       4.022572
    1      -70.491714  -70.491714  -70.491714  -70.491714     -70.491714
    2     -130.395354 -130.395354 -130.395354 -130.395354    -130.395354
3   0     -653.438708 -653.438708 -653.438708 -653.438708    -653.438708
    1       -9.072139   -9.072139   -9.072139   -9.072139      -9.072139
    2        2.580025    2.580025    2.580025    2.580025       2.580025
4   0        6.648153    6.648153    6.648153    6.648153       6.648153
    1      -39.573743  -39.573743  -39.573743  -39.573743     -39.573743
    2      -90.613203  -90.613203  -90.613203  -90.613203     -90.613203

           TensorizedChol   FasterQDA
obs clase
0   0         -497.025379 -497.025379
    1          -25.768385  -25.768385
    2            1.196574    1.196574
1   0         -195.240930 -195.240930
    1            2.237160    2.237160
    2          -10.876493  -10.876493
2   0            4.022572    4.022572
    1          -70.491714  -70.491714
    2         -130.395354 -130.395354
3   0         -653.438708 -653.438708
    1           -9.072139   -9.072139
    2            2.580025    2.580025
4   0            6.648153    6.648153
    1          -39.573743  -39.573743
    2          -90.613203  -90.613203

max |diff| de cualquier modelo contra QDA: 4.547473508864641e-13

                0   1   2   3   4   5   6   7   8   9   10  11  12  13  14
real             2   1   0   2   0   2   0   1   1   1   2   1   1   1   1
QDA              2   1   0   2   0   2   0   1   1   1   2   1   1   1   1
TensorizedQDA    2   1   0   2   0   2   0   1   1   1   2   1   1   1   1
FasterQDA        2   1   0   2   0   2   0   1   1   1   2   1   1   1   1
EfficientQDA     2   1   0   2   0   2   0   1   1   1   2   1   1   1   1
QDA_Chol1        2   1   0   2   0   2   0   1   1   1   2   1   1   1   1
QDA_Chol2        2   1   0   2   0   2   0   1   1   1   2   1   1   1   1
QDA_Chol3        2   1   0   2   0   2   0   1   1   1   2   1   1   1   1
TensorizedChol   2   1   0   2   0   2   0   1   1   1   2   1   1   1   1
EfficientChol    2   1   0   2   0   2   0   1   1   1   2   1   1   1   1

todas las predicciones coinciden: True